"""Run the importer over the real STEP files in fixtures/real/ and write
docs/real-files.md with what happened to each.

Those files are not committed (their licences do not allow it), so this report
is how we track whether core copes with real-world exports. Later it will also
run `kyumi diff` on the v1/v2 pairs in fixtures/real/pairs/.

    python core/real_files.py
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

from kyumi import load
from kyumi.package import import_step
from kyumi.reader import UnreadableFile

ROOT = Path(__file__).resolve().parents[1]
REAL = ROOT / "fixtures" / "real"
REPORT = ROOT / "docs" / "real-files.md"


def report_line(step: Path, out_dir: Path) -> str:
    """One table row: counts, time and size, or the error message."""
    out = out_dir / (step.stem + ".kyumi")
    try:
        timings = import_step(step, out)
    except Exception as error:  # noqa: BLE001 (any failure is a result worth recording)
        reason = (
            str(error) if isinstance(error, UnreadableFile) else f"{type(error).__name__}: {error}"
        )
        return f"| {step.relative_to(REAL)} | failed: {reason} | | | | |"
    model = load(out)
    seconds = sum(timings.values())
    size_mb = out.stat().st_size / 1e6
    groups = len(model.groups_by_fingerprint())
    return (
        f"| {step.relative_to(REAL)} | ok | {len(model.nodes)} | {len(model.shapes)} ({groups} "
        f"distinct geometries) | {seconds:.1f} s | {size_mb:.1f} MB |"
    )


def main() -> None:
    steps = sorted(p for p in REAL.rglob("*") if p.suffix.lower() in (".step", ".stp"))
    lines = [
        "# Real files",
        "",
        "Generated by `python core/real_files.py` from the files in `fixtures/real/`",
        "(not committed). Re-run after changing the importer.",
        "",
    ]
    if not steps:
        lines.append("No STEP files found in `fixtures/real/`.")
    else:
        lines += [
            "| file | import | nodes | shapes | time | .kyumi size |",
            "|---|---|---|---|---|---|",
        ]
        with tempfile.TemporaryDirectory() as tmp:
            for step in steps:
                print(step.relative_to(REAL), file=sys.stderr)
                lines.append(report_line(step, Path(tmp)))
    REPORT.write_text("\n".join(lines) + "\n")
    print(f"wrote {REPORT.relative_to(ROOT)} ({len(steps)} files)")


if __name__ == "__main__":
    main()
